# Site settings
baseurl = "/"
themesDir = "themes"
languageCode = "en-us"
title = "scott stavinoha"
theme = "hyde"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Scott Stavinoha"
	description = ""
	bio = "CS Student . けん玉 "
	email = "howdy@scotty.dance"
	# Enter optionally your twitter account
	#twitter = "Your Twitter account"
	enableRSS = false

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = "scott did a thing"
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/scottscavinsova"
    facebook = "https://www.facebook.com/scott.stavinoha"
    github   = "https://www.github.com/scottstav"
