version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scotty-dot-dance"
s3_bucket = "aws-sam-cli-scotty-dot-dance"
s3_prefix = "scotty-dot-dance"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
